//! Messages accepted by the application update dispatcher.

use super::{
    install::InstallAttempt,
    launch::{LaunchAttempt, LaunchAuthCheck},
    navigation::{
        InstanceTab, ModpackTab, NewInstanceTab, Route, SettingsTab, VersionFilter, WizardStep,
    },
};
use crate::{
    domain::{
        DownloadSource, InstanceColor, JavaRuntime, LoaderKind, OfflineAccount, PipelineEvent,
    },
    services::{
        auth::microsoft,
        catalog::{CatalogProject, CatalogProvider, CatalogRelease},
        content::{ContentEntry, ContentKind},
        insights::{InstanceScanSummary, ServicePing, VersionHighlights},
        launcher,
        loader_catalog::{self, LoaderCatalogKey},
        minecraft,
        modpack::ModpackPlan,
        system_resources::SystemResources,
        thumbnail,
    },
};
use iced::window;
use std::path::PathBuf;
use uuid::Uuid;

#[derive(Debug, Clone)]
pub enum Message {
    Navigate(Route),
    WindowOpened(window::Id),
    WindowLocated(Option<window::Id>),
    WindowResized(window::Id),
    WindowMaximizedChanged(bool),
    DragWindow,
    ResizeWindow(window::Direction),
    ToggleMaximize,
    MinimizeWindow,
    CloseWindow,
    AccountInputChanged(String),
    AddOfflineAccount,
    BeginMicrosoftLogin,
    MicrosoftDeviceAuthorizationLoaded(u64, Result<microsoft::DeviceAuthorization, String>),
    CopyMicrosoftLoginCode,
    MicrosoftLoginFinished(u64, Result<OfflineAccount, String>),
    CancelMicrosoftLogin,
    LaunchMicrosoftAccountChecked(
        LaunchAuthCheck,
        Result<OfflineAccount, microsoft::AccountRefreshError>,
    ),
    RetryLaunchAuthentication,
    CancelLaunchAuthentication,
    LaunchAuthenticationBackdropPressed,
    SelectAccount(Uuid),
    DeleteAccount(Uuid),
    WizardStepSelected(WizardStep),
    WizardNext,
    WizardBack,
    VersionFilterSelected(VersionFilter),
    OpenHighlightedVersion(VersionFilter, String),
    VersionSearchChanged(String),
    VersionPicked(String),
    LoaderPicked(LoaderKind),
    LoaderVersionPicked(String),
    WizardNameChanged(String),
    WizardDescriptionChanged(String),
    WizardColorPicked(InstanceColor),
    VersionsLoaded(Result<Vec<minecraft::VersionEntry>, String>),
    LoaderCatalogLoaded(
        u64,
        LoaderCatalogKey,
        Result<loader_catalog::LoaderCatalog, String>,
    ),
    RetryLoaderCatalog,
    JavaLoaded(Vec<JavaRuntime>),
    InsightsLoaded(u64, InstanceScanSummary),
    HighlightsLoaded(Result<VersionHighlights, String>),
    PingsLoaded(Vec<ServicePing>),
    ContentLoaded(Uuid, ContentKind, Result<Vec<ContentEntry>, String>),
    ContentQueryChanged(String),
    ContentThumbnailsLoaded(
        Uuid,
        ContentKind,
        Vec<(PathBuf, Option<thumbnail::Thumbnail>)>,
    ),
    ThumbnailsLoaded(Vec<(String, Option<thumbnail::Thumbnail>)>),
    OpenResourceBrowser(ContentKind),
    CloseResourceBrowser,
    ResourceQueryChanged(String),
    ResourceProviderPicked(CatalogProvider),
    SearchResources,
    ResourceSearchLoaded(u64, u64, Result<Vec<CatalogProject>, String>),
    ResourceProjectPicked(CatalogProject),
    ResourceBackToProjects,
    ResourceFilesLoaded(u64, u64, Result<Vec<CatalogRelease>, String>),
    ResourceFilePicked(CatalogRelease),
    ResourceDownloaded(u64, Uuid, ContentKind, Result<PathBuf, String>),
    ModpackQueryChanged(String),
    ModpackProviderPicked(CatalogProvider),
    SearchModpacks,
    ModpackSearchLoaded(u64, Result<Vec<CatalogProject>, String>),
    ModpackProjectPicked(CatalogProject),
    ModpackBackToProjects,
    ModpackFilesLoaded(u64, Result<Vec<CatalogRelease>, String>),
    ModpackFilePicked(CatalogRelease),
    ChooseLocalModpack,
    LocalModpackPicked(Option<PathBuf>),
    LocalModpackInspected(PathBuf, Result<ModpackPlan, String>),
    InstallLocalModpack,
    RefreshJava,
    RefreshPings,
    RefreshSystemResources,
    SystemResourcesLoaded(SystemResources),
    InstanceVersionFilesRepaired,
    SelectInstance(Uuid),
    SelectInstanceTab(InstanceTab),
    EditInstanceName(String),
    EditInstanceDescription(String),
    EditInstanceColor(InstanceColor),
    ToggleInstanceFavorite(bool),
    SetInstanceIsolation(bool),
    SetInstanceAutoJava(bool),
    SetInstanceJava(PathBuf),
    SetInstanceWidth(u32),
    SetInstanceHeight(u32),
    SetInstanceFullscreen(bool),
    SetInstanceAutoMemory(bool),
    SetInstanceMemory(u32),
    SetInstanceWindowTitle(String),
    SetInstanceCustomInfo(String),
    OpenPath(PathBuf),
    PathOpened(Result<(), String>),
    OpenFolder(PathBuf),
    FolderOpened(Result<(), String>),
    RevealPath(PathBuf),
    PathRevealed(Result<(), String>),
    OpenExternalUrl(&'static str),
    ExternalUrlOpened(Result<(), String>),
    DeleteInstance(Uuid),
    CancelDeleteInstance,
    ConfirmDeleteInstance,
    Deleted(Uuid, Result<(), String>),
    SettingsTabSelected(SettingsTab),
    NewInstanceTabSelected(NewInstanceTab),
    ModpackTabSelected(ModpackTab),
    DownloadSourcePicked(DownloadSource),
    DownloadConcurrencyChanged(u16),
    CancelInstall(Uuid),
    RetryInstall(Uuid),
    Pipeline(InstallAttempt, Box<PipelineEvent>),
    LaunchSelected,
    LaunchEvent(LaunchAttempt, launcher::LaunchEvent),
    DismissNotice,
}
