//! Messages accepted by the application update dispatcher.

use super::{
    install::InstallAttempt,
    launch::{LaunchAttempt, LaunchAuthCheck},
    navigation::{ModpackTab, NewInstanceTab, Route, SettingsTab, VersionFilter, WizardStep},
};
use crate::{
    domain::{
        DownloadSource, InstanceColor, JavaRuntime, LoaderKind, OfflineAccount, PipelineEvent,
    },
    services::{
        auth::microsoft,
        catalog::{CatalogProject, CatalogProvider, CatalogRelease},
        content::{ContentEntry, ContentKind},
        insights::{InstanceScanSummary, ServicePing, VersionHighlights},
        launcher,
        loader_catalog::{self, LoaderCatalogKey},
        minecraft,
        modpack::ModpackPlan,
        system_resources::SystemResources,
        thumbnail,
    },
};
use iced::window;
use std::path::PathBuf;
use uuid::Uuid;

#[derive(Debug, Clone)]
pub enum Message {
    Navigate(Route),
    WindowOpened(window::Id),
    WindowLocated(Option<window::Id>),
    WindowResized(window::Id),
    WindowMaximizedChanged(bool),
    DragWindow,
    ResizeWindow(window::Direction),
    ToggleMaximize,
    MinimizeWindow,
    CloseWindow,
    AccountInputChanged(String),
    AddOfflineAccount,
    BeginMicrosoftLogin,
    MicrosoftDeviceAuthorizationLoaded(u64, Result<microsoft::DeviceAuthorization, String>),
    CopyMicrosoftLoginCode,
    MicrosoftLoginFinished(u64, Result<OfflineAccount, String>),
    CancelMicrosoftLogin,
    RefreshMicrosoftAccount(Uuid),
    MicrosoftAccountRefreshed(Uuid, Result<OfflineAccount, microsoft::AccountRefreshError>),
    MicrosoftAccountAppearanceLoaded(Uuid, Result<microsoft::MinecraftTokenValidation, String>),
    LaunchMicrosoftTokenValidated(
        LaunchAuthCheck,
        Result<microsoft::MinecraftTokenValidation, String>,
    ),
    LaunchMicrosoftAccountRefreshed(
        LaunchAuthCheck,
        Result<OfflineAccount, microsoft::AccountRefreshError>,
    ),
    RetryLaunchAuthentication,
    ReauthenticateLaunchAccount,
    CancelLaunchAuthentication,
    LaunchAuthenticationBackdropPressed,
    SelectAccount(Uuid),
    DeleteAccount(Uuid),
    WizardStepSelected(WizardStep),
    WizardNext,
    WizardBack,
    VersionFilterSelected(VersionFilter),
    OpenHighlightedVersion(VersionFilter, String),
    VersionSearchChanged(String),
    VersionPicked(String),
    LoaderPicked(LoaderKind),
    LoaderVersionPicked(String),
    WizardNameChanged(String),
    WizardDescriptionChanged(String),
    WizardColorPicked(InstanceColor),
    VersionsLoaded(Result<Vec<minecraft::VersionEntry>, String>),
    LoaderCatalogLoaded(
        u64,
        LoaderCatalogKey,
        Result<loader_catalog::LoaderCatalog, String>,
    ),
    RetryLoaderCatalog,
    JavaLoaded(Vec<JavaRuntime>),
    InsightsLoaded(u64, InstanceScanSummary),
    HighlightsLoaded(Result<VersionHighlights, String>),
    PingsLoaded(Vec<ServicePing>),
    ContentLoaded(u64, Uuid, ContentKind, Result<Vec<ContentEntry>, String>),
    ContentQueryChanged(String),
    ContentThumbnailsLoaded(
        u64,
        Uuid,
        ContentKind,
        Vec<(PathBuf, Option<thumbnail::Thumbnail>)>,
    ),
    ThumbnailsLoaded(Vec<(String, Option<thumbnail::Thumbnail>)>),
    OpenResourceBrowser(Uuid, ContentKind),
    CloseResourceBrowser,
    ResourceQueryChanged(String),
    ResourceProviderPicked(CatalogProvider),
    SearchResources,
    ResourceSearchLoaded(u64, u64, Result<Vec<CatalogProject>, String>),
    ResourceProjectPicked(CatalogProject),
    ResourceBackToProjects,
    ResourceFilesLoaded(u64, u64, Result<Vec<CatalogRelease>, String>),
    ResourceFilePicked(CatalogRelease),
    ResourceDownloaded(u64, Uuid, ContentKind, Result<PathBuf, String>),
    ModpackQueryChanged(String),
    ModpackProviderPicked(CatalogProvider),
    SearchModpacks,
    ModpackSearchLoaded(u64, Result<Vec<CatalogProject>, String>),
    ModpackProjectPicked(CatalogProject),
    ModpackBackToProjects,
    ModpackFilesLoaded(u64, Result<Vec<CatalogRelease>, String>),
    ModpackFilePicked(CatalogRelease),
    ChooseLocalModpack,
    LocalModpackPicked(Option<PathBuf>),
    LocalModpackInspected(PathBuf, Result<ModpackPlan, String>),
    InstallLocalModpack,
    RefreshJava,
    RefreshPings,
    RefreshSystemResources,
    SystemResourcesLoaded(SystemResources),
    InstanceVersionFilesRepaired,
    EditInstanceName(Uuid, String),
    EditInstanceDescription(Uuid, String),
    EditInstanceColor(Uuid, InstanceColor),
    ToggleInstanceFavorite(Uuid, bool),
    SetInstanceIsolation(Uuid, bool),
    SetInstanceAutoJava(Uuid, bool),
    SetInstanceJava(Uuid, PathBuf),
    SetInstanceWidth(Uuid, u32),
    SetInstanceHeight(Uuid, u32),
    SetInstanceFullscreen(Uuid, bool),
    SetInstanceAutoMemory(Uuid, bool),
    SetInstanceMemory(Uuid, u32),
    SetInstanceWindowTitle(Uuid, String),
    SetInstanceCustomInfo(Uuid, String),
    OpenPath(PathBuf),
    PathOpened(Result<(), String>),
    OpenFolder(PathBuf),
    FolderOpened(Result<(), String>),
    RevealPath(PathBuf),
    PathRevealed(Result<(), String>),
    OpenExternalUrl(&'static str),
    ExternalUrlOpened(Result<(), String>),
    DeleteInstance(Uuid),
    CancelDeleteInstance(Uuid),
    ConfirmDeleteInstance(Uuid),
    Deleted(Uuid, Result<(), String>),
    SettingsTabSelected(SettingsTab),
    NewInstanceTabSelected(NewInstanceTab),
    ModpackTabSelected(ModpackTab),
    DownloadSourcePicked(DownloadSource),
    DownloadConcurrencyChanged(u16),
    CancelInstall(InstallAttempt),
    RetryInstall(InstallAttempt),
    Pipeline(InstallAttempt, Box<PipelineEvent>),
    LaunchInstance(Uuid),
    LaunchEvent(LaunchAttempt, launcher::LaunchEvent),
    DismissNotice,
}
